# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b35749c50391f8339c055310b01a911f84e3b66b9b6c194fe6722850dc1b2eb4ee69fff39ac71749ca483768cb80611e15615aa0510ca23eef4727816880c4

test:
  secret_key_base: 60f4fc43cb8ef619dfc8173fdd65ee56dc5001b1df02dd34dd0c6ee55bb4d216d51510746e0b04879f7cc42f2ee76f526415ea0058a4bef7db4a9b2dab580474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

